#!/usr/bin/env ruby

include SprayDatumHelper

create_spray_datum('2012-11-07 16:30:13', 'BE03 - MAKHUBELE MS', {:accuracy=>"5", :lat=>"-23.82168442", :lng=>"30.16113748", :homestead_sprayed=>true, :sprayer_id=>"BE03 - MAKHUBELE MS", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>15, :ddt_sprayed_shelters_1=>12, :ddt_refill_1=>true, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Simba T R", :unsprayed_rooms=>8, :unsprayed_shelters=>5})
create_spray_datum('2012-11-07 17:03:08', 'BE02 - MABUNDA YW', {:accuracy=>"5", :lat=>"-23.81972577", :lng=>"30.30440348", :homestead_sprayed=>true, :sprayer_id=>"BE02 - MABUNDA YW", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>7, :pyrethroid_sprayed_shelters_1=>8, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Simba T R", :unsprayed_rooms=>44, :unsprayed_shelters=>85})
create_spray_datum('2012-11-07 17:19:14', 'BW01 - CHAUKE MR', {:accuracy=>"5", :lat=>"-23.77202789", :lng=>"30.39038133", :homestead_sprayed=>true, :sprayer_id=>"BW01 - CHAUKE MR", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>12, :ddt_sprayed_shelters_1=>5, :ddt_refill_1=>true, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Risimati H L", :unsprayed_rooms=>8, :unsprayed_shelters=>5})
create_spray_datum('2012-11-07 18:22:36', 'BE04 - MARINGA HW', {:accuracy=>"10", :lat=>"-23.63509498", :lng=>"30.49364637", :homestead_sprayed=>true, :sprayer_id=>"BE04 - MARINGA HW", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>14, :ddt_sprayed_shelters_1=>41, :ddt_refill_1=>false, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>8, :unsprayed_shelters=>11})
create_spray_datum('2012-11-07 18:28:20', 'BE03 - MAKHUBELE MS', {:accuracy=>"5", :lat=>"-23.63122072", :lng=>"30.4947733", :homestead_sprayed=>true, :sprayer_id=>"BE03 - MAKHUBELE MS", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>12, :ddt_sprayed_shelters_1=>5, :ddt_refill_1=>true, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Simba T R", :unsprayed_rooms=>11, :unsprayed_shelters=>5})
create_spray_datum('2012-11-07 18:36:22', 'BW02 - MABASA MJ', {:accuracy=>"5", :lat=>"-23.63278573", :lng=>"30.49383527", :homestead_sprayed=>true, :sprayer_id=>"BW02 - MABASA MJ", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>10, :pyrethroid_sprayed_shelters_1=>10, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Tshsikhawe M R", :unsprayed_rooms=>10, :unsprayed_shelters=>8})
create_spray_datum('2012-11-07 18:45:11', 'LTT-D02 - NEMAKHAVHANI PW', {:accuracy=>"5", :lat=>"-23.63495215", :lng=>"30.49370998", :homestead_sprayed=>true, :sprayer_id=>"LTT-D02 - NEMAKHAVHANI PW", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>7, :pyrethroid_sprayed_shelters_1=>8, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Tshsikhawe M R", :unsprayed_rooms=>16, :unsprayed_shelters=>9})
