#!/usr/bin/env ruby

include SprayDatumHelper
include WorkerHelper

create_worker(1, 'a', 'Active')
create_worker(2, 'b', 'Inactive')
create_worker(3, 'c', 'Inactive')
create_worker(4, 'd', 'Inactive')
create_worker(5, 'e', 'Inactive')
create_worker(6, 'f', 'Inactive')
create_worker(7, 'g', 'Inactive')
create_worker(8, 'h', 'Inactive')
create_worker(9, 'i', 'Inactive')
create_worker(10, 'j', 'Inactive')

create_spray_datum('2012-11-07 16:30:13', 'BE03 - MAKHUBELE MS', {:accuracy=>"5", :lat=>"-23.82168442", :lng=>"30.16113748", :homestead_sprayed=>true, :sprayer_id=>"BE03 - MAKHUBELE MS", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>15, :ddt_sprayed_shelters_1=>12, :ddt_refill_1=>true, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Simba T R", :unsprayed_rooms=>8, :unsprayed_shelters=>5})
create_spray_datum('2012-11-07 17:03:08', 'BE02 - MABUNDA YW', {:accuracy=>"5", :lat=>"-23.81972577", :lng=>"30.30440348", :homestead_sprayed=>true, :sprayer_id=>"BE02 - MABUNDA YW", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>7, :pyrethroid_sprayed_shelters_1=>8, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Simba T R", :unsprayed_rooms=>44, :unsprayed_shelters=>85})
create_spray_datum('2012-11-07 17:19:14', 'BW01 - CHAUKE MR', {:accuracy=>"5", :lat=>"-23.77202789", :lng=>"30.39038133", :homestead_sprayed=>true, :sprayer_id=>"BW01 - CHAUKE MR", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>12, :ddt_sprayed_shelters_1=>5, :ddt_refill_1=>true, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Risimati H L", :unsprayed_rooms=>8, :unsprayed_shelters=>5})
create_spray_datum('2012-11-07 18:22:36', 'BE04 - MARINGA HW', {:accuracy=>"10", :lat=>"-23.63509498", :lng=>"30.49364637", :homestead_sprayed=>true, :sprayer_id=>"BE04 - MARINGA HW", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>14, :ddt_sprayed_shelters_1=>41, :ddt_refill_1=>false, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>8, :unsprayed_shelters=>11})
create_spray_datum('2012-11-07 18:28:20', 'BE03 - MAKHUBELE MS', {:accuracy=>"5", :lat=>"-23.63122072", :lng=>"30.4947733", :homestead_sprayed=>true, :sprayer_id=>"BE03 - MAKHUBELE MS", :ddt_used_1=>true, :ddt_sprayed_rooms_1=>12, :ddt_sprayed_shelters_1=>5, :ddt_refill_1=>true, :pyrethroid_used_1=>false, :pyrethroid_sprayed_rooms_1=>0, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>false, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Simba T R", :unsprayed_rooms=>11, :unsprayed_shelters=>5})
create_spray_datum('2012-11-07 18:36:22', 'BW02 - MABASA MJ', {:accuracy=>"5", :lat=>"-23.63278573", :lng=>"30.49383527", :homestead_sprayed=>true, :sprayer_id=>"BW02 - MABASA MJ", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>10, :pyrethroid_sprayed_shelters_1=>10, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Tshsikhawe M R", :unsprayed_rooms=>10, :unsprayed_shelters=>8})
create_spray_datum('2012-11-07 18:45:11', 'LTT-D02 - NEMAKHAVHANI PW', {:accuracy=>"5", :lat=>"-23.63495215", :lng=>"30.49370998", :homestead_sprayed=>true, :sprayer_id=>"LTT-D02 - NEMAKHAVHANI PW", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>7, :pyrethroid_sprayed_shelters_1=>8, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Tshsikhawe M R", :unsprayed_rooms=>16, :unsprayed_shelters=>9})
create_spray_datum('2012-11-14 08:50:47', 'MGW29 - HADZHI NR', {:accuracy=>"10", :lat=>"-23.02218511", :lng=>"30.60618102", :homestead_sprayed=>true, :sprayer_id=>"MGW29 - HADZHI NR", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>1, :pyrethroid_sprayed_shelters_1=>1, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 09:13:36', 'MGE06 - MAKUMBANE TE', {:accuracy=>"5", :lat=>"-23.02299116", :lng=>"30.60412259", :homestead_sprayed=>true, :sprayer_id=>"MGE06 - MAKUMBANE TE", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>6, :pyrethroid_sprayed_shelters_1=>0, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 09:32:02', 'MGW29 - HADZHI NR', {:accuracy=>"5", :lat=>"-23.02303755", :lng=>"30.60413468", :homestead_sprayed=>true, :sprayer_id=>"MGW29 - HADZHI NR", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>1, :pyrethroid_sprayed_shelters_1=>4, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 09:46:31', 'MGE06 - MAKUMBANE TE', {:accuracy=>"5", :lat=>"-23.02248298", :lng=>"30.60370262", :homestead_sprayed=>true, :sprayer_id=>"MGE06 - MAKUMBANE TE", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>4, :pyrethroid_sprayed_shelters_1=>1, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 10:24:05', 'MGW29 - HADZHI NR', {:accuracy=>"10", :lat=>"-23.02106412", :lng=>"30.60356636", :homestead_sprayed=>true, :sprayer_id=>"MGW29 - HADZHI NR", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>20, :pyrethroid_sprayed_shelters_1=>2, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 10:34:13', 'MGE06 - MAKUMBANE TE', {:accuracy=>"5", :lat=>"-23.02089493", :lng=>"30.60342876", :homestead_sprayed=>true, :sprayer_id=>"MGE06 - MAKUMBANE TE", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>13, :pyrethroid_sprayed_shelters_1=>2, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Silima R N", :unsprayed_rooms=>3, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 10:51:59', 'T3745 - MUDAUAR', {:accuracy=>"5", :lat=>"-23.03478677", :lng=>"30.65145514", :homestead_sprayed=>true, :sprayer_id=>"T3745 - MUDAUAR", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>50, :pyrethroid_sprayed_shelters_1=>10, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Risimati H L", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 10:56:25', 'T3746 - BALOYI.J', {:accuracy=>"10", :lat=>"-23.03475804", :lng=>"30.6514606", :homestead_sprayed=>true, :sprayer_id=>"T3746 - BALOYI.J", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>54, :pyrethroid_sprayed_shelters_1=>8, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Risimati H L", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 10:56:38', 'SH01 - CHAUKE KP', {:accuracy=>"4235", :lat=>"-23.0837128", :lng=>"30.6651451", :homestead_sprayed=>true, :sprayer_id=>"SH01 - CHAUKE KP", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>19, :pyrethroid_sprayed_shelters_1=>4, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Munyamela T E", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
create_spray_datum('2012-11-14 11:01:49', 'T3748 - MALULEKE MJ', {:accuracy=>"10", :lat=>"-23.03480555", :lng=>"30.65146989", :homestead_sprayed=>true, :sprayer_id=>"T3748 - MALULEKE MJ", :ddt_used_1=>false, :ddt_sprayed_rooms_1=>0, :ddt_sprayed_shelters_1=>0, :ddt_refill_1=>false, :pyrethroid_used_1=>true, :pyrethroid_sprayed_rooms_1=>53, :pyrethroid_sprayed_shelters_1=>11, :pyrethroid_refill_1=>true, :ddt_used_2=>false, :ddt_sprayed_rooms_2=>0, :ddt_sprayed_shelters_2=>0, :ddt_refill_2=>false, :pyrethroid_used_2=>false, :pyrethroid_sprayed_rooms_2=>0, :pyrethroid_sprayed_shelters_2=>0, :pyrethroid_refill_2=>false, :foreman=>"Risimati H L", :unsprayed_rooms=>0, :unsprayed_shelters=>0})
