#!/usr/bin/env ruby

include SprayDatumHelper

create_spray_datum('2012-11-7 16:30:13', 'BE03 - MAKHUBELE MS', {:accuracy=>"5", :lat=>"-23.82168442", :lng=>"30.16113748", :homestead_sprayed=>"TRUE", :sprayer_id=>"BE03 - MAKHUBELE MS", :DDT_used_1=>"TRUE", :DDT_sprayed_rooms_1=>"15", :DDT_sprayed_shelters_1=>"12", :DDT_refill_1=>"TRUE", :pyrethroid_used_1=>"FALSE", :pyrethroid_sprayed_rooms_1=>"", :pyrethroid_sprayed_shelters_1=>"", :pyrethroid_refill_1=>"", :DDT_used_2=>"FALSE", :DDT_sprayed_rooms_2=>"", :DDT_sprayed_shelters_2=>"", :DDT_refill_2=>"", :pyrethroid_used_2=>"FALSE", :pyrethroid_sprayed_rooms_2=>"", :pyrethroid_sprayed_shelters_2=>"", :pyrethroid_refill_2=>"", :foreman=>"Simba T R", :unsprayed_rooms=>"8", :unsprayed_shelters=>"5"})
create_spray_datum('2012-11-7 17:3:8', 'BE02 - MABUNDA YW', {:accuracy=>"5", :lat=>"-23.81972577", :lng=>"30.30440348", :homestead_sprayed=>"TRUE", :sprayer_id=>"BE02 - MABUNDA YW", :DDT_used_1=>"FALSE", :DDT_sprayed_rooms_1=>"", :DDT_sprayed_shelters_1=>"", :DDT_refill_1=>"", :pyrethroid_used_1=>"TRUE", :pyrethroid_sprayed_rooms_1=>"7", :pyrethroid_sprayed_shelters_1=>"8", :pyrethroid_refill_1=>"TRUE", :DDT_used_2=>"FALSE", :DDT_sprayed_rooms_2=>"", :DDT_sprayed_shelters_2=>"", :DDT_refill_2=>"", :pyrethroid_used_2=>"FALSE", :pyrethroid_sprayed_rooms_2=>"", :pyrethroid_sprayed_shelters_2=>"", :pyrethroid_refill_2=>"", :foreman=>"Simba T R", :unsprayed_rooms=>"44", :unsprayed_shelters=>"85"})
create_spray_datum('2012-11-7 17:19:14', 'BW01 - CHAUKE MR', {:accuracy=>"5", :lat=>"-23.77202789", :lng=>"30.39038133", :homestead_sprayed=>"TRUE", :sprayer_id=>"BW01 - CHAUKE MR", :DDT_used_1=>"TRUE", :DDT_sprayed_rooms_1=>"12", :DDT_sprayed_shelters_1=>"5", :DDT_refill_1=>"TRUE", :pyrethroid_used_1=>"FALSE", :pyrethroid_sprayed_rooms_1=>"", :pyrethroid_sprayed_shelters_1=>"", :pyrethroid_refill_1=>"", :DDT_used_2=>"FALSE", :DDT_sprayed_rooms_2=>"", :DDT_sprayed_shelters_2=>"", :DDT_refill_2=>"", :pyrethroid_used_2=>"FALSE", :pyrethroid_sprayed_rooms_2=>"", :pyrethroid_sprayed_shelters_2=>"", :pyrethroid_refill_2=>"", :foreman=>"Risimati H L", :unsprayed_rooms=>"8", :unsprayed_shelters=>"5"})
create_spray_datum('2012-11-7 18:22:36', 'BE04 - MARINGA HW', {:accuracy=>"10", :lat=>"-23.63509498", :lng=>"30.49364637", :homestead_sprayed=>"TRUE", :sprayer_id=>"BE04 - MARINGA HW", :DDT_used_1=>"TRUE", :DDT_sprayed_rooms_1=>"14", :DDT_sprayed_shelters_1=>"41", :DDT_refill_1=>"FALSE", :pyrethroid_used_1=>"FALSE", :pyrethroid_sprayed_rooms_1=>"", :pyrethroid_sprayed_shelters_1=>"", :pyrethroid_refill_1=>"", :DDT_used_2=>"FALSE", :DDT_sprayed_rooms_2=>"", :DDT_sprayed_shelters_2=>"", :DDT_refill_2=>"", :pyrethroid_used_2=>"FALSE", :pyrethroid_sprayed_rooms_2=>"", :pyrethroid_sprayed_shelters_2=>"", :pyrethroid_refill_2=>"", :foreman=>"Silima R N", :unsprayed_rooms=>"8", :unsprayed_shelters=>"11"})
create_spray_datum('2012-11-7 18:28:20', 'BE03 - MAKHUBELE MS', {:accuracy=>"5", :lat=>"-23.63122072", :lng=>"30.4947733", :homestead_sprayed=>"TRUE", :sprayer_id=>"BE03 - MAKHUBELE MS", :DDT_used_1=>"TRUE", :DDT_sprayed_rooms_1=>"12", :DDT_sprayed_shelters_1=>"5", :DDT_refill_1=>"TRUE", :pyrethroid_used_1=>"FALSE", :pyrethroid_sprayed_rooms_1=>"", :pyrethroid_sprayed_shelters_1=>"", :pyrethroid_refill_1=>"", :DDT_used_2=>"FALSE", :DDT_sprayed_rooms_2=>"", :DDT_sprayed_shelters_2=>"", :DDT_refill_2=>"", :pyrethroid_used_2=>"FALSE", :pyrethroid_sprayed_rooms_2=>"", :pyrethroid_sprayed_shelters_2=>"", :pyrethroid_refill_2=>"", :foreman=>"Simba T R", :unsprayed_rooms=>"11", :unsprayed_shelters=>"5"})
